version: '3.8'

services:
  bot:
    image: vpn-bot.cr.cloud.ru/vpn-telegram-bot:latest
    container_name: vpn_bot
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - db_data:/app/data

volumes:
  db_data:
