version: '3.8'

services:
  bot:
    image: vpn-bot.cr.cloud.ru/vpn-telegram-bot:latest
    container_name: vpn_bot
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/vpn_bot
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: vpn_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
